apiVersion: v1
kind: Service
metadata:
  labels:
    app: nginx
  annotations:
    argocd.argoproj.io/sync-wave: "3"  
  name: nginx
  namespace: default
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: nginx
  type: NodePort
